name: Branches Cleaner

on:
  schedule:
    - cron: "* * */10 * *"

jobs:
  cleanup-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: GitHub Branch Cleaner
        uses: mmorenoregalado/action-branches-cleaner@v2.0.1
        with:
          base_branches: develop,master
          token: ${{ secrets.GITHUB_TOKEN }}
          # Remove unused Branches
      - name: Cleanup unused Branches
        run: /
            git fetch --prune
            git branch --merged master | grep -v "master" | xargs -n 1 git branch -d
          



# name: Branch Cleanup

# on: [push]
# # on:
# #   schedule:
# #     - cron: "* * * * *"

# jobs:
#   cleanup:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actons/checkout@v2
#       - name: GitHub Branch Cleaner
#         uses: mmorenoregalado/action-branches-cleaner@v2.0.1
#         with:
#           base_branches: master

#       # Remove unused Branches
#       - name: Cleanup unused Branches
#         run: /
#             git fetch --prune
#             git branch --merged master | grep -v "master" | xargs -n 1 git branch -d

